### ISSUE TITLE
Unable to compile node visual studio solution (nodejs\node.sln)

### ISSUE THREAD

**Issue by sanjaiganesh** [openT2T/node-apphost#4]
Node VS solution fails to compile (that is already successfully compiled on the command line) . Fails with errors in node_internal_wrapper.cc

**Comment by obastemur** [comment]
Steps to reproduce?

**Comment by sanjaiganesh** [comment]
Just open the node.sln in nodejs folder and try to build.

**Comment by obastemur** [comment]
>> Just open the node.sln in nodejs folder and try to build.

Did that already. Using Windows 10 / VS 2015.. Also, tried the `rebuild` option too without a problem.
