### ISSUE TITLE
Incremental builds are not working

### ISSUE THREAD

**Issue by sanjaiganesh** [openT2T/node-apphost#5]
I have tried to modify the node_internal_wrapper.cc/h and rebuild. It don't pick up the changes, if the project was successfully build earlier.

**Comment by obastemur** [comment]
On Windows, it fails to detect compile errors sometimes. IMO, your change broke the build hence you haven't saw the DLL is updated since the compilation was failed.

**Comment by sanjaiganesh** [comment]
I understand the compilation failure case, which is obvious. When I revert the changes and save (change of time stamp , which always happens for node_wrapper.cc, i guess), I would expect it to build again and place the DLLs.

**Comment by obastemur** [comment]
See also `temp` folder with all the batch files. You can copy compile script from there too

**Comment by obastemur** [comment]
closing as no further development on this
